[phases.setup]
nixPkgs = ['php81', 'php81Packages.composer']

[phases.build]
cmds = ['echo "No build step required for PHP"']

[phases.start]
cmd = 'php -S 0.0.0.0:$PORT -t backend/'

[variables]
PHP_VERSION = '8.1'